// Generated by CoffeeScript 1.10.0
(function() {
  var parseResponse, postsHtml, renderImagePost, renderMediaPost, renderPage, renderPostType, renderTextPost;

  $(function() {
    var url;
    url = "http://api.are.na/v2/channels/arena-influences/contents?page=1&per=20";
    return $.getJSON(url, function(response) {
      console.log('results received', response);
      parseResponse(response.contents);
      return renderPage(postsHtml);
    });
  });

  postsHtml = "";

  parseResponse = function(response) {
    var i, len, post, results;
    results = [];
    for (i = 0, len = response.length; i < len; i++) {
      post = response[i];
      results.push(renderPostType(post));
    }
    return results;
  };

  renderPostType = function(post) {
    switch (post["class"]) {
      case "Image":
        return postsHtml += renderImagePost(post);
      case "Text":
        return postsHtml += renderTextPost(post);
      case "Media":
        return postsHtml += renderMediaPost(post);
      default:
        return console.log("unknown post type", post["class"], post);
    }
  };

  renderImagePost = function(post) {
    var html;
    return html = "<div id='" + post.id + "' class='post imagepost col-md-12'> <img src='" + post.image.large.url + "' class='img-responsive' /> </div>";
  };

  renderTextPost = function(post) {
    var html;
    return html = "<div id='" + post.id + "' class='post textpost col-md-10 col-md-offset-1'> <h1>" + post.generated_title + "</h1> " + post.content_html + " </div>";
  };

  renderMediaPost = function(post) {
    var html;
    return html = "<div id='" + post.id + "' class='col-md-6 col-md-offset-3'> " + post.embed.html + " </div>";
  };

  renderPage = function(html) {
    return $('#posts-container').append(html);
  };

}).call(this);
